In [ ]:
from synrxn import DataLoader
from pathlib import Path
dl = DataLoader(task="classification", source="zenodo", version="0.0.6",
                cache_dir=Path("~/.cache/synrxn").expanduser())
print(dl.available_names())
df = dl.load('schneider_b')  
df.head()

In [ ]:
from synrxn import DataLoader
from pathlib import Path
dl = DataLoader(task="synth", source="zenodo", version="0.0.6",
                cache_dir=Path("~/.cache/synrxn").expanduser())
print(dl.available_names())
df = dl.load('schneider_b')  
df.head()

In [ ]:
from synrxn import DataLoader
from pathlib import Path
dl = DataLoader(task="classification", source="zenodo", version="0.0.6",
                cache_dir=Path("~/.cache/synrxn").expanduser())
print(dl.available_names())
df = dl.load('schneider_b')  
df.head()

In [ ]:
from synrxn.data import DataLoader
from pathlib import Path
dl = DataLoader(task="class", source="github", version="v0.0.6",
                cache_dir=Path("~/.cache/synrxn").expanduser(),gh_enable=True)
print(dl.available_names())
df = dl.load('schneider_b')  
df.head()

In [ ]:
from synrxn.data import DataLoader
from pathlib import Path
dl = DataLoader(task="classification", source="commit", version="3e1612e2199e8b0e369fce3ed9aff3dda68e4c32" ,
                cache_dir=Path("~/.cache/synrxn").expanduser(),gh_enable=True)
print(dl.available_names())
df = dl.load('schneider_b')  
df.head()

In [73]:
from synrxn.data import DataLoader
from pathlib import Path
dl = DataLoader(task="aam", source="commit", version="latest" ,
                cache_dir=Path("~/.cache/synrxn").expanduser(),gh_enable=True)
print(dl.available_names())
df = dl.load('ecoli')  
df.head()

['ecoli', 'golden', 'natcomm', 'recon3d', 'uspto_3k']

,r_id,ground_truth,rxn_mapper,graphormer,local_mapper,rdt,rxn,original_id
0,ecoli_1,[C:2]([C:5](=[O:11])[CH2:15][CH2:12][C:10]([O-...,[O:14]=[C:13]([O-:15])[C:12](=[O:11])[CH2:5][C...,[CH3:18][CH:17]([CH3:19])[CH2:16][CH:14]([NH2:...,[O:14]=[C:13]([O-:15])[C:12](=[O:11])[CH2:5][C...,[O:1]=[C:2]([O-:3])[C:4](=[O:5])[CH2:6][CH2:7]...,CC(C)CC(N)C(=O)O.O=C([O-])CCC(=O)C(=O)[O-]>>CC...,ecoli_1
1,ecoli_2,[OH:1][CH2:3][CH:5]([OH:2])[CH3:4]>>[O:1]=[CH:...,[OH:1][C@H:3]([CH3:2])[CH2:4][OH:5]>>[OH2:1].[...,[C@@H:2]([CH2:4][OH:5])([OH:1])[CH3:3]>>[O:5]=...,[OH:1][C@H:3]([CH3:2])[CH2:4][OH:5]>>[OH2:1].[...,[OH:1][CH2:2][C@H:3]([OH:4])[CH3:5]>>[O:1]=[CH...,CC(O)CO>>CCC=O.O,ecoli_2
2,ecoli_3,[NH3+:1][CH:3]([C:6]([O-:4])=[O:5])[CH:7]([CH2...,[O:1]=[C:2]([O-:3])[C@@H:4]([NH3+:5])[C@H:6]([...,[O-:3][C:2]([C@H:4]([C@@H:6]([CH2:8][OH:9])[OH...,[O:1]=[C:2]([O-:3])[C@@H:4]([NH3+:5])[C@H:6]([...,[O:1]=[C:2]([O-:3])[C@@H:4]([NH3+:5])[C@H:6]([...,[NH3+]C(C(=O)[O-])C(O)CO>>O=CCO.[NH3+]CC(=O)[O-],ecoli_3
3,ecoli_4,[NH3+:1][CH:4]([CH:5]([OH:2])[CH2:14][O:12][P:...,[O:1]=[C:2]([O-:3])[C@@H:4]([NH3+:5])[C@H:6]([...,[O-:12][P:10]([O-:13])(=[O:11])[O:9][CH2:8][C@...,[O:1]=[C:2]([O-:3])[C@@H:4]([NH3+:5])[C@H:6]([...,[O:1]=[C:2]([O-:3])[C@@H:4]([NH3+:5])[C@H:6]([...,O.[NH3+]C(C(=O)[O-])C(O)COP(=O)([O-])[O-]>>O=P...,ecoli_4
4,ecoli_5,[CH:1]1([CH3:14])[O:6][CH:7]([n:17]2[cH:18][n:...,[CH3:1][C@H:2]1[O:3][C@@H:4]([n:16]2[c:15]3[n:...,[OH2:19].[c:10]1([c:12]2[c:6]([n:7][cH:8][n:9]...,[CH3:1][C@H:2]1[O:3][C@@H:4]([n:16]2[c:15]3[n:...,[OH:1][C@@H:2]1[C@H:3]([OH:4])[C@H:5]([O:6][C@...,CC1OC(n2cnc3c(N)ncnc32)C(O)C1O.O>>CC1OC(O)C(O)...,ecoli_5

In [ ]:
from synrxn.split.repeated_kfold import RepeatedKFoldsSplitter
from synrxn.data import DataLoader
from pathlib import Path
dl = DataLoader(task="prop", source="commit", version="latest" ,
                cache_dir=Path("~/.cache/synrxn").expanduser(),gh_enable=True)
df = dl.load("b97xd3")
splitter = RepeatedKFoldsSplitter(n_splits=5, n_repeats=2, ratio=(8,1,1), shuffle=True, random_state=1)
splitter.prepare_splits(df, stratify=None)
train_df, val_df, test_df = splitter.get_split(repeat=1, fold=1, as_frame=True)
train_df.head(2)

In [ ]:
from synrxn.split.repeated_kfold import RepeatedKFoldsSplitter
from synrxn.data import DataLoader
from pathlib import Path
dl = DataLoader(task="prop", source="commit", version="latest" ,
                cache_dir=Path("~/.cache/synrxn").expanduser(),gh_enable=True)
df = dl.load("cycloadd")
# splitter = RepeatedKFoldsSplitter(n_splits=5, n_repeats=2, ratio=(8,1,1), shuffle=True, random_state=1)
# splitter.prepare_splits(df, stratify=None)
# train_df, val_df, test_df = splitter.get_split(repeat=1, fold=1, as_frame=True)
# train_df.head(2)

df

In [ ]:
import pandas as pd

data = pd.read_csv('./Data/raw/23/full_dataset.csv')
data

In [53]:
import pandas as pd

df = pd.read_csv('./Data/raw/pericyclic/cyclo_data_v2_16072024.csv')
data = df.to_dict('records')
data[0]

{'idx': 0,
 'code': 0,
 'reaction': '[C:1](=[C:2]([C:3]([H:13])([H:14])[H:15])[H:12])([H:10])[H:11].[C:4](#[N+:5][C-:6]([C:7]([H:17])([H:18])[H:19])[C:8]#[N:9])[H:16]>>[C:1]1([H:10])([H:11])[C:2]([C:3]([H:13])([H:14])[H:15])([H:12])[C:4]([H:16])=[N:5][C:6]1([C:7]([H:17])([H:18])[H:19])[C:8]#[N:9]'}

In [54]:
from joblib import Parallel, delayed
from synkit.IO import rsmi_to_its
from synkit.Graph.Feature.graph_descriptors import GraphDescriptor
from synkit.Graph.Feature.wl_hash import WLHash


def add_ring(value):
    value = dict(value)  
    try:
        rc = rsmi_to_its(value["reaction"], core=True)

        value["ring"] = GraphDescriptor.get_cycle_member_rings(rc)
        value['wl'] = WLHash().weisfeiler_lehman_graph_hash(rc)
        value['rc'] = rc
    except Exception as e:
        value["ring"] = None
        value["ring_error"] = str(e)
    return value


data = Parallel(n_jobs=4, verbose=2, backend="loky")(
    delayed(add_ring)(value) for value in data
)

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  56 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done 5776 tasks      | elapsed:    7.7s
[Parallel(n_jobs=4)]: Done 5953 out of 5953 | elapsed:    8.0s finished

In [55]:
import pandas as pd

pd.DataFrame(data)['ring'].value_counts()

ring
[]        5255
[5, 5]     650
[5]         48
Name: count, dtype: int64

In [57]:
check = [value for value in data if value['ring']==[5]]
check[0]

{'idx': 2,
 'code': 1,
 'reaction': '[C:1](#[C:2][C:3]([H:14])([H:15])[H:16])[H:13].[C:4]([C:5](=[O:6])[C:7]#[N+:8][O-:9])([H:10])([H:11])[H:12]>>[C:1]1([H:13])=[C:2]([C:3]([H:14])([H:15])[H:16])[O:9][N:8]=[C:7]1[C:5]([C:4]([H:10])([H:11])[H:12])=[O:6]',
 'ring': [5],
 'wl': 'fd3ab307c28256924579eb7489dfc2ab',
 'rc': <networkx.classes.graph.Graph at 0x7fec09471050>}

In [ ]:
clean = [value for value in data if value['ring']==[]]
clean[0]

In [64]:
data_8 = [value for value in data if value['class']==8]
data_8

[{'idx': 18,
  'code': 11,
  'reaction': '[C:10](=[N+:11]([C-:12]([C:13]([H:18])([H:19])[H:20])[H:17])[H:16])([H:14])[H:15].[F:1][C:2]1=[C:3]([F:4])[C:5]2([H:21])[C:6]([H:22])=[C:7]([H:23])[C:8]1([H:24])[O:9]2>>[F:1][C:2]12[C:3]([F:4])([C:5]3([H:21])[C:6]([H:22])=[C:7]([H:23])[C:8]1([H:24])[O:9]3)[C:12]([C:13]([H:18])([H:19])[H:20])([H:17])[N:11]([H:16])[C:10]2([H:14])[H:15]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec0a3d1110>,
  'class': 8},
 {'idx': 19,
  'code': 11,
  'reaction': '[C:10](=[N+:11]([C-:12]([C:13]([H:18])([H:19])[H:20])[H:17])[H:16])([H:14])[H:15].[F:1][C:2]1=[C:3]([F:4])[C:5]2([H:21])[C:6]([H:22])=[C:7]([H:23])[C:8]1([H:24])[O:9]2>>[F:1][C:2]1=[C:3]([F:4])[C:5]2([H:21])[C:6]3([H:22])[C:7]([H:23])([C:8]1([H:24])[O:9]2)[C:12]([C:13]([H:18])([H:19])[H:20])([H:17])[N:11]([H:16])[C:10]3([H:14])[H:15]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec28316690>,
  'class': 8},
 {'idx': 163,
  'code': 82,
  'reaction': '[C:9]([C:10]([C:11]([H:20])([H:21])[H:22])=[N+:12]([C:13]([H:23])([H:24])[H:25])[C-:14]([C:15]([H:26])([H:27])[H:28])[C:16]([H:29])([H:30])[H:31])([H:17])([H:18])[H:19].[Cl:1][C:2]1=[C:3]([H:32])[C:4]2([H:33])[C:5]([H:34])=[C:6]([H:35])[C:7]1([H:36])[O:8]2>>[Cl:1][C:2]1=[C:3]([H:32])[C:4]2([H:33])[C:5]3([H:34])[C:6]([H:35])([C:7]1([H:36])[O:8]2)[C:14]([C:15]([H:26])([H:27])[H:28])([C:16]([H:29])([H:30])[H:31])[N:12]([C:13]([H:23])([H:24])[H:25])[C:10]3([C:9]([H:17])([H:18])[H:19])[C:11]([H:20])([H:21])[H:22]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec231d24d0>,
  'class': 8},
 {'idx': 164,
  'code': 82,
  'reaction': '[C:9]([C:10]([C:11]([H:20])([H:21])[H:22])=[N+:12]([C:13]([H:23])([H:24])[H:25])[C-:14]([C:15]([H:26])([H:27])[H:28])[C:16]([H:29])([H:30])[H:31])([H:17])([H:18])[H:19].[Cl:1][C:2]1=[C:3]([H:32])[C:4]2([H:33])[C:5]([H:34])=[C:6]([H:35])[C:7]1([H:36])[O:8]2>>[Cl:1][C:2]12[C:3]([H:32])([C:4]3([H:33])[C:5]([H:34])=[C:6]([H:35])[C:7]1([H:36])[O:8]3)[C:14]([C:15]([H:26])([H:27])[H:28])([C:16]([H:29])([H:30])[H:31])[N:12]([C:13]([H:23])([H:24])[H:25])[C:10]2([C:9]([H:17])([H:18])[H:19])[C:11]([H:20])([H:21])[H:22]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec085b14d0>,
  'class': 8},
 {'idx': 182,
  'code': 91,
  'reaction': '[C:12]([C:13](=[N+:14]([C-:15]([C:16]([C:17]([H:25])([H:26])[H:27])=[O:18])[H:24])[H:23])[H:22])([H:19])([H:20])[H:21].[C:1]([O:2][C:3]1=[C:4]([C:5]#[N:6])[C:7]2([H:31])[C:8]([H:32])=[C:9]([H:33])[C:10]1([H:34])[O:11]2)([H:28])([H:29])[H:30]>>[C:1]([O:2][C:3]12[C:4]([C:5]#[N:6])([C:7]3([H:31])[C:8]([H:32])=[C:9]([H:33])[C:10]1([H:34])[O:11]3)[C:13]([C:12]([H:19])([H:20])[H:21])([H:22])[N:14]([H:23])[C:15]2([C:16]([C:17]([H:25])([H:26])[H:27])=[O:18])[H:24])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec2317b710>,
  'class': 8},
 {'idx': 183,
  'code': 91,
  'reaction': '[C:12]([C:13](=[N+:14]([C-:15]([C:16]([C:17]([H:25])([H:26])[H:27])=[O:18])[H:24])[H:23])[H:22])([H:19])([H:20])[H:21].[C:1]([O:2][C:3]1=[C:4]([C:5]#[N:6])[C:7]2([H:31])[C:8]([H:32])=[C:9]([H:33])[C:10]1([H:34])[O:11]2)([H:28])([H:29])[H:30]>>[C:1]([O:2][C:3]1=[C:4]([C:5]#[N:6])[C:7]2([H:31])[C:8]3([H:32])[C:9]([H:33])([C:10]1([H:34])[O:11]2)[C:13]([C:12]([H:19])([H:20])[H:21])([H:22])[N:14]([H:23])[C:15]3([C:16]([C:17]([H:25])([H:26])[H:27])=[O:18])[H:24])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec23183310>,
  'class': 8},
 {'idx': 184,
  'code': 91,
  'reaction': '[C:12]([C:13](=[N+:14]([C-:15]([C:16]([C:17]([H:25])([H:26])[H:27])=[O:18])[H:24])[H:23])[H:22])([H:19])([H:20])[H:21].[C:1]([O:2][C:3]1=[C:4]([C:5]#[N:6])[C:7]2([H:31])[C:8]([H:32])=[C:9]([H:33])[C:10]1([H:34])[O:11]2)([H:28])([H:29])[H:30]>>[C:1]([O:2][C:3]1=[C:4]([C:5]#[N:6])[C:7]2([H:31])[C:8]3([H:32])[C:9]([H:33])([C:10]1([H:34])[O:11]2)[C:15]([C:16]([C:17]([H:25])([H:26])[H:27])=[O:18])([H:24])[N:14]([H:23])[C:13]3([C:12]([H:19])([H:20])[H:21])[H:22])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec23182850>,
  'class': 8},
 {'idx': 185,
  'code': 91,
  'reaction': '[C:12]([C:13](=[N+:14]([C-:15]([C:16]([C:17]([H:25])([H:26])[H:27])=[O:18])[H:24])[H:23])[H:22])([H:19])([H:20])[H:21].[C:1]([O:2][C:3]1=[C:4]([C:5]#[N:6])[C:7]2([H:31])[C:8]([H:32])=[C:9]([H:33])[C:10]1([H:34])[O:11]2)([H:28])([H:29])[H:30]>>[C:1]([O:2][C:3]12[C:4]([C:5]#[N:6])([C:7]3([H:31])[C:8]([H:32])=[C:9]([H:33])[C:10]1([H:34])[O:11]3)[C:15]([C:16]([C:17]([H:25])([H:26])[H:27])=[O:18])([H:24])[N:14]([H:23])[C:13]2([C:12]([H:19])([H:20])[H:21])[H:22])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec231a4510>,
  'class': 8},
 {'idx': 229,
  'code': 112,
  'reaction': '[C:9]([N:10]([C:11](=[O:12])[C:13]([C:14]([H:23])([H:24])[H:25])=[N+:15]([C-:16]([C:17]([H:27])([H:28])[H:29])[C:18]([H:30])([H:31])[H:32])[H:26])[H:22])([H:19])([H:20])[H:21].[F:1][C:2]1=[C:3]([H:33])[C:4]2([H:34])[C:5]([H:35])=[C:6]([H:36])[C:7]1([H:37])[O:8]2>>[F:1][C:2]1=[C:3]([H:33])[C:4]2([H:34])[C:5]3([H:35])[C:6]([H:36])([C:7]1([H:37])[O:8]2)[C:16]([C:17]([H:27])([H:28])[H:29])([C:18]([H:30])([H:31])[H:32])[N:15]([H:26])[C:13]3([C:11]([N:10]([C:9]([H:19])([H:20])[H:21])[H:22])=[O:12])[C:14]([H:23])([H:24])[H:25]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22ede150>,
  'class': 8},
 {'idx': 230,
  'code': 112,
  'reaction': '[C:9]([N:10]([C:11](=[O:12])[C:13]([C:14]([H:23])([H:24])[H:25])=[N+:15]([C-:16]([C:17]([H:27])([H:28])[H:29])[C:18]([H:30])([H:31])[H:32])[H:26])[H:22])([H:19])([H:20])[H:21].[F:1][C:2]1=[C:3]([H:33])[C:4]2([H:34])[C:5]([H:35])=[C:6]([H:36])[C:7]1([H:37])[O:8]2>>[F:1][C:2]1=[C:3]([H:33])[C:4]2([H:34])[C:5]3([H:35])[C:6]([H:36])([C:7]1([H:37])[O:8]2)[C:13]([C:11]([N:10]([C:9]([H:19])([H:20])[H:21])[H:22])=[O:12])([C:14]([H:23])([H:24])[H:25])[N:15]([H:26])[C:16]3([C:17]([H:27])([H:28])[H:29])[C:18]([H:30])([H:31])[H:32]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22ed1450>,
  'class': 8},
 {'idx': 231,
  'code': 112,
  'reaction': '[C:9]([N:10]([C:11](=[O:12])[C:13]([C:14]([H:23])([H:24])[H:25])=[N+:15]([C-:16]([C:17]([H:27])([H:28])[H:29])[C:18]([H:30])([H:31])[H:32])[H:26])[H:22])([H:19])([H:20])[H:21].[F:1][C:2]1=[C:3]([H:33])[C:4]2([H:34])[C:5]([H:35])=[C:6]([H:36])[C:7]1([H:37])[O:8]2>>[F:1][C:2]12[C:3]([H:33])([C:4]3([H:34])[C:5]([H:35])=[C:6]([H:36])[C:7]1([H:37])[O:8]3)[C:16]([C:17]([H:27])([H:28])[H:29])([C:18]([H:30])([H:31])[H:32])[N:15]([H:26])[C:13]2([C:11]([N:10]([C:9]([H:19])([H:20])[H:21])[H:22])=[O:12])[C:14]([H:23])([H:24])[H:25]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22ed0650>,
  'class': 8},
 {'idx': 232,
  'code': 112,
  'reaction': '[C:9]([N:10]([C:11](=[O:12])[C:13]([C:14]([H:23])([H:24])[H:25])=[N+:15]([C-:16]([C:17]([H:27])([H:28])[H:29])[C:18]([H:30])([H:31])[H:32])[H:26])[H:22])([H:19])([H:20])[H:21].[F:1][C:2]1=[C:3]([H:33])[C:4]2([H:34])[C:5]([H:35])=[C:6]([H:36])[C:7]1([H:37])[O:8]2>>[F:1][C:2]12[C:3]([H:33])([C:4]3([H:34])[C:5]([H:35])=[C:6]([H:36])[C:7]1([H:37])[O:8]3)[C:13]([C:11]([N:10]([C:9]([H:19])([H:20])[H:21])[H:22])=[O:12])([C:14]([H:23])([H:24])[H:25])[N:15]([H:26])[C:16]2([C:17]([H:27])([H:28])[H:29])[C:18]([H:30])([H:31])[H:32]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22ed2150>,
  'class': 8},
 {'idx': 286,
  'code': 137,
  'reaction': '[C:11]([C-:12]([N+:13]([C:14]([H:23])([H:24])[H:25])=[C:15]([C:16]([H:26])([H:27])[H:28])[C:17]#[N:18])[H:22])([H:19])([H:20])[H:21].[N:1]#[C:2][C:3]1=[C:4]([Cl:5])[C:6]2([H:29])[C:7]([H:30])([H:31])[C:8]([H:32])([H:33])[C:9]1([H:34])[C:10]2([H:35])[H:36]>>[N:1]#[C:2][C:3]12[C:4]([Cl:5])([C:6]3([H:29])[C:7]([H:30])([H:31])[C:8]([H:32])([H:33])[C:9]1([H:34])[C:10]3([H:35])[H:36])[C:15]([C:16]([H:26])([H:27])[H:28])([C:17]#[N:18])[N:13]([C:14]([H:23])([H:24])[H:25])[C:12]2([C:11]([H:19])([H:20])[H:21])[H:22]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22b38e10>,
  'class': 8},
 {'idx': 287,
  'code': 137,
  'reaction': '[C:11]([C-:12]([N+:13]([C:14]([H:23])([H:24])[H:25])=[C:15]([C:16]([H:26])([H:27])[H:28])[C:17]#[N:18])[H:22])([H:19])([H:20])[H:21].[N:1]#[C:2][C:3]1=[C:4]([Cl:5])[C:6]2([H:29])[C:7]([H:30])([H:31])[C:8]([H:32])([H:33])[C:9]1([H:34])[C:10]2([H:35])[H:36]>>[N:1]#[C:2][C:3]12[C:4]([Cl:5])([C:6]3([H:29])[C:7]([H:30])([H:31])[C:8]([H:32])([H:33])[C:9]1([H:34])[C:10]3([H:35])[H:36])[C:12]([C:11]([H:19])([H:20])[H:21])([H:22])[N:13]([C:14]([H:23])([H:24])[H:25])[C:15]2([C:16]([H:26])([H:27])[H:28])[C:17]#[N:18]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22b37250>,
  'class': 8},
 {'idx': 288,
  'code': 138,
  'reaction': '[C:11]([C:12](=[O:13])[C-:14]([N+:15]([C:16]([H:24])([H:25])[H:26])=[C:17]([C:18]#[N:19])[H:27])[H:23])([H:20])([H:21])[H:22].[C:1]([O:2][C:3]1=[C:4]([C:5]([H:31])([H:32])[H:33])[C:6]2([H:34])[C:7]([H:35])=[C:8]([H:36])[C:9]1([H:37])[O:10]2)([H:28])([H:29])[H:30]>>[C:1]([O:2][C:3]1=[C:4]([C:5]([H:31])([H:32])[H:33])[C:6]2([H:34])[C:7]3([H:35])[C:8]([H:36])([C:9]1([H:37])[O:10]2)[C:17]([C:18]#[N:19])([H:27])[N:15]([C:16]([H:24])([H:25])[H:26])[C:14]3([C:12]([C:11]([H:20])([H:21])[H:22])=[O:13])[H:23])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22b68810>,
  'class': 8},
 {'idx': 289,
  'code': 138,
  'reaction': '[C:11]([C:12](=[O:13])[C-:14]([N+:15]([C:16]([H:24])([H:25])[H:26])=[C:17]([C:18]#[N:19])[H:27])[H:23])([H:20])([H:21])[H:22].[C:1]([O:2][C:3]1=[C:4]([C:5]([H:31])([H:32])[H:33])[C:6]2([H:34])[C:7]([H:35])=[C:8]([H:36])[C:9]1([H:37])[O:10]2)([H:28])([H:29])[H:30]>>[C:1]([O:2][C:3]1=[C:4]([C:5]([H:31])([H:32])[H:33])[C:6]2([H:34])[C:7]3([H:35])[C:8]([H:36])([C:9]1([H:37])[O:10]2)[C:14]([C:12]([C:11]([H:20])([H:21])[H:22])=[O:13])([H:23])[N:15]([C:16]([H:24])([H:25])[H:26])[C:17]3([C:18]#[N:19])[H:27])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22b6ae90>,
  'class': 8},
 {'idx': 290,
  'code': 138,
  'reaction': '[C:11]([C:12](=[O:13])[C-:14]([N+:15]([C:16]([H:24])([H:25])[H:26])=[C:17]([C:18]#[N:19])[H:27])[H:23])([H:20])([H:21])[H:22].[C:1]([O:2][C:3]1=[C:4]([C:5]([H:31])([H:32])[H:33])[C:6]2([H:34])[C:7]([H:35])=[C:8]([H:36])[C:9]1([H:37])[O:10]2)([H:28])([H:29])[H:30]>>[C:1]([O:2][C:3]12[C:4]([C:5]([H:31])([H:32])[H:33])([C:6]3([H:34])[C:7]([H:35])=[C:8]([H:36])[C:9]1([H:37])[O:10]3)[C:17]([C:18]#[N:19])([H:27])[N:15]([C:16]([H:24])([H:25])[H:26])[C:14]2([C:12]([C:11]([H:20])([H:21])[H:22])=[O:13])[H:23])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22b8de90>,
  'class': 8},
 {'idx': 291,
  'code': 138,
  'reaction': '[C:11]([C:12](=[O:13])[C-:14]([N+:15]([C:16]([H:24])([H:25])[H:26])=[C:17]([C:18]#[N:19])[H:27])[H:23])([H:20])([H:21])[H:22].[C:1]([O:2][C:3]1=[C:4]([C:5]([H:31])([H:32])[H:33])[C:6]2([H:34])[C:7]([H:35])=[C:8]([H:36])[C:9]1([H:37])[O:10]2)([H:28])([H:29])[H:30]>>[C:1]([O:2][C:3]12[C:4]([C:5]([H:31])([H:32])[H:33])([C:6]3([H:34])[C:7]([H:35])=[C:8]([H:36])[C:9]1([H:37])[O:10]3)[C:14]([C:12]([C:11]([H:20])([H:21])[H:22])=[O:13])([H:23])[N:15]([C:16]([H:24])([H:25])[H:26])[C:17]2([C:18]#[N:19])[H:27])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22bb0090>,
  'class': 8},
 {'idx': 337,
  'code': 160,
  'reaction': '[C:9](=[N+:10]([C:11]([H:21])([H:22])[H:23])[C-:12]([C:13]([C:14]([H:24])([H:25])[H:26])=[O:15])[C:16]([C:17]([H:27])([H:28])[H:29])=[O:18])([H:19])[H:20].[Cl:1][C:2]1=[C:3]([H:30])[C:4]2([H:31])[C:5]([H:32])([H:33])[C:6]([H:34])([H:35])[C:7]1([H:36])[C:8]2([H:37])[H:38]>>[Cl:1][C:2]12[C:3]([H:30])([C:4]3([H:31])[C:5]([H:32])([H:33])[C:6]([H:34])([H:35])[C:7]1([H:36])[C:8]3([H:37])[H:38])[C:12]([C:13]([C:14]([H:24])([H:25])[H:26])=[O:15])([C:16]([C:17]([H:27])([H:28])[H:29])=[O:18])[N:10]([C:11]([H:21])([H:22])[H:23])[C:9]2([H:19])[H:20]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22c0ac50>,
  'class': 8},
 {'idx': 338,
  'code': 160,
  'reaction': '[C:9](=[N+:10]([C:11]([H:21])([H:22])[H:23])[C-:12]([C:13]([C:14]([H:24])([H:25])[H:26])=[O:15])[C:16]([C:17]([H:27])([H:28])[H:29])=[O:18])([H:19])[H:20].[Cl:1][C:2]1=[C:3]([H:30])[C:4]2([H:31])[C:5]([H:32])([H:33])[C:6]([H:34])([H:35])[C:7]1([H:36])[C:8]2([H:37])[H:38]>>[Cl:1][C:2]12[C:3]([H:30])([C:4]3([H:31])[C:5]([H:32])([H:33])[C:6]([H:34])([H:35])[C:7]1([H:36])[C:8]3([H:37])[H:38])[C:9]([H:19])([H:20])[N:10]([C:11]([H:21])([H:22])[H:23])[C:12]2([C:13]([C:14]([H:24])([H:25])[H:26])=[O:15])[C:16]([C:17]([H:27])([H:28])[H:29])=[O:18]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec231f3210>,
  'class': 8},
 {'idx': 345,
  'code': 164,
  'reaction': '[C:13]([C-:14]([N+:15](=[C:16]([C:17]([H:25])([H:26])[H:27])[C:18]#[N:19])[H:24])[H:23])([H:20])([H:21])[H:22].[C:1]([C:2]1=[C:3]([C:4]([F:5])([F:6])[F:7])[C:8]2([H:31])[C:9]([H:32])([H:33])[C:10]([H:34])([H:35])[C:11]1([H:36])[C:12]2([H:37])[H:38])([H:28])([H:29])[H:30]>>[C:1]([C:2]12[C:3]([C:4]([F:5])([F:6])[F:7])([C:8]3([H:31])[C:9]([H:32])([H:33])[C:10]([H:34])([H:35])[C:11]1([H:36])[C:12]3([H:37])[H:38])[C:16]([C:17]([H:25])([H:26])[H:27])([C:18]#[N:19])[N:15]([H:24])[C:14]2([C:13]([H:20])([H:21])[H:22])[H:23])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22935550>,
  'class': 8},
 {'idx': 346,
  'code': 164,
  'reaction': '[C:13]([C-:14]([N+:15](=[C:16]([C:17]([H:25])([H:26])[H:27])[C:18]#[N:19])[H:24])[H:23])([H:20])([H:21])[H:22].[C:1]([C:2]1=[C:3]([C:4]([F:5])([F:6])[F:7])[C:8]2([H:31])[C:9]([H:32])([H:33])[C:10]([H:34])([H:35])[C:11]1([H:36])[C:12]2([H:37])[H:38])([H:28])([H:29])[H:30]>>[C:1]([C:2]12[C:3]([C:4]([F:5])([F:6])[F:7])([C:8]3([H:31])[C:9]([H:32])([H:33])[C:10]([H:34])([H:35])[C:11]1([H:36])[C:12]3([H:37])[H:38])[C:14]([C:13]([H:20])([H:21])[H:22])([H:23])[N:15]([H:24])[C:16]2([C:17]([H:25])([H:26])[H:27])[C:18]#[N:19])([H:28])([H:29])[H:30]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22934910>,
  'class': 8},
 {'idx': 347,
  'code': 165,
  'reaction': '[C:1]([C:2]1=[C:3]([H:24])[C:4]2([H:25])[C:5]([H:26])([H:27])[C:6]([H:28])([H:29])[C:7]1([H:30])[C:8]2([H:31])[H:32])([H:21])([H:22])[H:23].[C:9]([O:10][C:11](=[O:12])[C-:13]([C:14]#[N:15])[N+:16]([C:17]([H:36])([H:37])[H:38])=[C:18]([C:19]#[N:20])[H:39])([H:33])([H:34])[H:35]>>[C:1]([C:2]12[C:3]([H:24])([C:4]3([H:25])[C:5]([H:26])([H:27])[C:6]([H:28])([H:29])[C:7]1([H:30])[C:8]3([H:31])[H:32])[C:18]([C:19]#[N:20])([H:39])[N:16]([C:17]([H:36])([H:37])[H:38])[C:13]2([C:11]([O:10][C:9]([H:33])([H:34])[H:35])=[O:12])[C:14]#[N:15])([H:21])([H:22])[H:23]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22933d10>,
  'class': 8},
 {'idx': 348,
  'code': 165,
  'reaction': '[C:1]([C:2]1=[C:3]([H:24])[C:4]2([H:25])[C:5]([H:26])([H:27])[C:6]([H:28])([H:29])[C:7]1([H:30])[C:8]2([H:31])[H:32])([H:21])([H:22])[H:23].[C:9]([O:10][C:11](=[O:12])[C-:13]([C:14]#[N:15])[N+:16]([C:17]([H:36])([H:37])[H:38])=[C:18]([C:19]#[N:20])[H:39])([H:33])([H:34])[H:35]>>[C:1]([C:2]12[C:3]([H:24])([C:4]3([H:25])[C:5]([H:26])([H:27])[C:6]([H:28])([H:29])[C:7]1([H:30])[C:8]3([H:31])[H:32])[C:13]([C:11]([O:10][C:9]([H:33])([H:34])[H:35])=[O:12])([C:14]#[N:15])[N:16]([C:17]([H:36])([H:37])[H:38])[C:18]2([C:19]#[N:20])[H:39])([H:21])([H:22])[H:23]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22cbc650>,
  'class': 8},
 {'idx': 349,
  'code': 166,
  'reaction': '[C:10]([C:11](=[O:12])[C:13](=[N+:14]([C-:15]([C:16]#[N:17])[H:25])[H:24])[C:18]([C:19]([H:26])([H:27])[H:28])=[O:20])([H:21])([H:22])[H:23].[C:1]([O:2][C:3]1=[C:4]([H:32])[C:5]2([H:33])[C:6]([H:34])=[C:7]([H:35])[C:8]1([H:36])[O:9]2)([H:29])([H:30])[H:31]>>[C:1]([O:2][C:3]12[C:4]([H:32])([C:5]3([H:33])[C:6]([H:34])=[C:7]([H:35])[C:8]1([H:36])[O:9]3)[C:15]([C:16]#[N:17])([H:25])[N:14]([H:24])[C:13]2([C:11]([C:10]([H:21])([H:22])[H:23])=[O:12])[C:18]([C:19]([H:26])([H:27])[H:28])=[O:20])([H:29])([H:30])[H:31]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22cbe250>,
  'class': 8},
 {'idx': 350,
  'code': 166,
  'reaction': '[C:10]([C:11](=[O:12])[C:13](=[N+:14]([C-:15]([C:16]#[N:17])[H:25])[H:24])[C:18]([C:19]([H:26])([H:27])[H:28])=[O:20])([H:21])([H:22])[H:23].[C:1]([O:2][C:3]1=[C:4]([H:32])[C:5]2([H:33])[C:6]([H:34])=[C:7]([H:35])[C:8]1([H:36])[O:9]2)([H:29])([H:30])[H:31]>>[C:1]([O:2][C:3]1=[C:4]([H:32])[C:5]2([H:33])[C:6]3([H:34])[C:7]([H:35])([C:8]1([H:36])[O:9]2)[C:13]([C:11]([C:10]([H:21])([H:22])[H:23])=[O:12])([C:18]([C:19]([H:26])([H:27])[H:28])=[O:20])[N:14]([H:24])[C:15]3([C:16]#[N:17])[H:25])([H:29])([H:30])[H:31]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22cafdd0>,
  'class': 8},
 {'idx': 351,
  'code': 166,
  'reaction': '[C:10]([C:11](=[O:12])[C:13](=[N+:14]([C-:15]([C:16]#[N:17])[H:25])[H:24])[C:18]([C:19]([H:26])([H:27])[H:28])=[O:20])([H:21])([H:22])[H:23].[C:1]([O:2][C:3]1=[C:4]([H:32])[C:5]2([H:33])[C:6]([H:34])=[C:7]([H:35])[C:8]1([H:36])[O:9]2)([H:29])([H:30])[H:31]>>[C:1]([O:2][C:3]1=[C:4]([H:32])[C:5]2([H:33])[C:6]3([H:34])[C:7]([H:35])([C:8]1([H:36])[O:9]2)[C:15]([C:16]#[N:17])([H:25])[N:14]([H:24])[C:13]3([C:11]([C:10]([H:21])([H:22])[H:23])=[O:12])[C:18]([C:19]([H:26])([H:27])[H:28])=[O:20])([H:29])([H:30])[H:31]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22c9ccd0>,
  'class': 8},
 {'idx': 352,
  'code': 166,
  'reaction': '[C:10]([C:11](=[O:12])[C:13](=[N+:14]([C-:15]([C:16]#[N:17])[H:25])[H:24])[C:18]([C:19]([H:26])([H:27])[H:28])=[O:20])([H:21])([H:22])[H:23].[C:1]([O:2][C:3]1=[C:4]([H:32])[C:5]2([H:33])[C:6]([H:34])=[C:7]([H:35])[C:8]1([H:36])[O:9]2)([H:29])([H:30])[H:31]>>[C:1]([O:2][C:3]12[C:4]([H:32])([C:5]3([H:33])[C:6]([H:34])=[C:7]([H:35])[C:8]1([H:36])[O:9]3)[C:13]([C:11]([C:10]([H:21])([H:22])[H:23])=[O:12])([C:18]([C:19]([H:26])([H:27])[H:28])=[O:20])[N:14]([H:24])[C:15]2([C:16]#[N:17])[H:25])([H:29])([H:30])[H:31]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22c9e190>,
  'class': 8},
 {'idx': 353,
  'code': 167,
  'reaction': '[C:11](=[N+:12]([C:13]([H:23])([H:24])[H:25])[C-:14]([C:15]#[N:16])[C:17](=[O:18])[N:19]([C:20]([H:27])([H:28])[H:29])[H:26])([H:21])[H:22].[N:1]#[C:2][C:3]1=[C:4]([F:5])[C:6]2([H:30])[C:7]([H:31])([H:32])[C:8]([H:33])([H:34])[C:9]1([H:35])[C:10]2([H:36])[H:37]>>[N:1]#[C:2][C:3]12[C:4]([F:5])([C:6]3([H:30])[C:7]([H:31])([H:32])[C:8]([H:33])([H:34])[C:9]1([H:35])[C:10]3([H:36])[H:37])[C:11]([H:21])([H:22])[N:12]([C:13]([H:23])([H:24])[H:25])[C:14]2([C:15]#[N:16])[C:17](=[O:18])[N:19]([C:20]([H:27])([H:28])[H:29])[H:26]',
  'ring': [],
  'wl': 'c08933ffc1894af2632136262732cec2',
  'rc': <networkx.classes.graph.Graph at 0x7fec22ae5210>,
  'class': 8},
 {'idx': 354,
  'code': 167,

In [59]:
from synkit.Graph.Matcher.graph_cluster import GraphCluster
from synkit.Utils.utils import stratified_random_sample

cls = GraphCluster()
result = cls.fit(data, rule_key='rc', attribute_key='wl')
temp = stratified_random_sample(result, property_key='class')

In [65]:
pd.DataFrame(result)['class'].value_counts().head(10)

class
8     1534
16     730
0      635
5      435
9      358
24     285
4      214
14     209
15     188
12     161
Name: count, dtype: int64

In [66]:
rc =data_8[0]['rc']

In [ ]:
rc = [value['rc'] for value in temp]

In [ ]:
from synkit.Vis.graph_visualizer import GraphVisualizer
import matplotlib.pyplot as plt
vis = GraphVisualizer()
fig = vis.visualize_its_grid(rc[:4], use_edge_color=True, subplot_shape=(2, 2))
plt.show()

In [ ]:
fig = vis.visualize_its_grid(rc[4:8], use_edge_color=True, subplot_shape=(2, 2))
plt.show()

In [ ]:
fig = vis.visualize_its_grid(rc[:6], use_edge_color=True, subplot_shape=(2, 3))
plt.show()

In [ ]:
EIGHT = [value for value in data if value['ring']==[4,4]]

In [ ]:
EIGHT

In [ ]:
rc = rsmi_to_its('[C:1]([C:2]([C:3](=[C:4]([H:34])[H:35])[H:33])=[C:7]([H:36])[H:37])([H:30])([H:31])[H:32].[C:5]1(=[C:6]([H:17])[H:18])[C:8](=[O:9])[C:10]([H:19])([H:20])[C:11]([H:21])([H:22])[C:12]([Br:13])([H:23])[C:14]1([C:15]([H:24])([H:25])[H:26])[C:16]([H:27])([H:28])[H:29]>>[C:1]([C:2]1=[C:3]([H:33])[C:4]([H:34])([H:35])[C@@:5]2([C:6]([H:17])([H:18])[C:7]1([H:36])[H:37])[C:8](=[O:9])[C:10]([H:19])([H:20])[C:11]([H:21])([H:22])[C@@:12]([Br:13])([H:23])[C:14]2([C:15]([H:24])([H:25])[H:26])[C:16]([H:27])([H:28])[H:29])([H:30])([H:31])[H:32]',
                 core=True)

In [72]:
len(raw)

5953

In [ ]:
from synkit.Graph import print_graph_attributes

print_graph_attributes(rc)

In [67]:
import pandas as pd
from synkit.Chem.Reaction.standardize import Standardize

raw = pd.read_csv('./Data/raw/pericyclic/cyclo_data_v2_16072024.csv')
raw = raw.to_dict('records')
for value in raw:
    rsmi = Standardize().fit(value['reaction'], remove_aam=True, ignore_stereo=True)
    r, p = rsmi.split('>>')
    value['r'], value['p'], value['rsmi'] = r, p, rsmi

In [ ]:
from synkit.Synthesis.Reactor.syn_reactor import SynReactor

reactor = SynReactor(substrate='C=C(Cl)C#N.C=CCCC12C=CC=CN1C=CC2=O', template=rc, explicit_h=False, implicit_temp=True)
reactor.smarts

In [69]:
from collections import defaultdict
from typing import Iterable, Optional

from synkit.Synthesis.Reactor.syn_reactor import SynReactor
from synkit.Chem.Reaction.standardize import Standardize


def group_rsmi(
    results: Iterable[str],
    *,
    std: Optional[Standardize] = None,
    remove_duplicates: bool = True,
    return_failed: bool = False,
):
    """
    Group original atom-mapped reaction SMILES by standardized unmapped RSMI.

    Parameters
    ----------
    results : Iterable[str]
        Atom-mapped reaction SMILES.
    std : Standardize, optional
        Existing Standardize instance. Reusing one is faster.
    remove_duplicates : bool, default=True
        Remove duplicate mapped RSMIs inside each group.
    return_failed : bool, default=False
        Also return failed standardizations.

    Returns
    -------
    dict[str, list[str]]
        standardized_unmapped_rsmi -> list of original mapped RSMIs

    Or, if return_failed=True:
        tuple[dict[str, list[str]], list[tuple[str, Exception]]]
    """
    std = std or Standardize()

    grouped = defaultdict(list)
    seen = defaultdict(set)
    failed = []

    for mapped_rsmi in results:
        try:
            key = std.fit(mapped_rsmi, remove_aam=True)

            if remove_duplicates:
                if mapped_rsmi in seen[key]:
                    continue
                seen[key].add(mapped_rsmi)

            grouped[key].append(mapped_rsmi)

        except Exception as exc:
            failed.append((mapped_rsmi, exc))

    grouped = dict(grouped)

    if return_failed:
        return grouped, failed

    return grouped

def rbl(
    rsmi: str,
    rc,
    *,
    std: Optional[Standardize] = None,
    remove_duplicates: bool = True,
    return_all: bool = True,
):
    """
    Find mapped reaction SMARTS from one reaction center `rc`
    that standardize to the given input RSMI.

    Parameters
    ----------
    rsmi : str
        Target reaction SMILES. Can be mapped or unmapped.
    rc :
        Reaction center / rule used by SynReactor.
    std : Standardize, optional
        Existing Standardize instance.
    remove_duplicates : bool, default=True
        Remove duplicate mapped candidates.
    return_all : bool, default=True
        If True, return all matching mapped RSMIs.
        If False, return only the first matching mapped RSMI.

    Returns
    -------
    list[str] | str | None
        Matching mapped RSMI candidates, one candidate, or None.
    """
    std = std or Standardize()

    target_rsmi = std.fit(rsmi, remove_aam=True)
    reactants, _ = target_rsmi.split(">>", 1)

    reactor = SynReactor(reactants, rc)
    candidates = reactor.smarts

    grouped = group_rsmi(
        candidates,
        std=std,
        remove_duplicates=remove_duplicates,
    )

    matches = grouped.get(target_rsmi)

    if not matches:
        return None

    if return_all:
        return matches

    return matches[0]

In [ ]:
rbl(rsmi=value['rsmi'], rc=rc, return_all=False)

In [70]:
for value in raw:
    new = rbl(rsmi=value['rsmi'], rc=rc, return_all=False)
    value['new_rsmi'] = new

2026-05-14 11:50:01,981 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:01,983 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:01,985 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:01,987 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:01,988 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:01,990 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:01,992 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:01,996 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:01,999 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,002 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,004 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,006 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,008 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,009 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,011 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,013 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,015 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,017 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,019 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,023 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,027 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,029 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,031 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,033 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,035 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,037 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,039 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,041 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,043 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,045 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,047 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,049 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,051 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,053 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,055 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,057 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,059 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,061 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,063 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,065 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,067 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,069 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,071 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,073 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,075 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,077 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,079 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,081 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,083 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,085 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,087 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,089 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,091 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,093 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,095 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,097 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,099 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,101 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,102 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,104 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,106 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,108 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,110 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,112 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,114 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,116 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,118 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,121 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,123 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,125 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,127 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,129 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,132 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,134 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,137 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,139 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,141 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,143 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,145 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,147 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,149 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,152 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,154 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,156 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,158 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,160 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,162 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,164 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,166 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,169 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,171 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,174 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,176 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,179 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,181 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,183 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,185 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,187 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,189 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,192 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,194 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,196 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,200 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,202 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,204 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,207 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,209 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,211 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,214 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,216 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,218 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,220 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,222 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,225 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,227 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,230 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,233 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,235 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,237 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,239 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,242 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,244 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,246 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,248 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,250 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,252 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,254 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,256 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,258 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,260 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,262 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,265 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,269 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,272 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,274 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,276 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,278 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,279 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,282 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,284 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,287 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,289 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,291 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,293 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,295 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,297 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,300 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,302 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,305 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,307 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,310 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,312 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,314 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,316 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,318 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,320 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,322 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,324 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,327 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,329 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,331 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,334 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,336 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,338 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,343 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,348 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,351 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,353 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,356 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,358 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,360 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,363 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,366 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,369 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,372 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,375 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,380 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,383 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,387 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,389 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,391 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,394 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,397 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,403 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,408 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,414 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,419 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,421 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,424 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,426 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,428 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,431 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,433 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,435 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,438 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,440 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,443 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,445 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,447 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,449 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,452 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,454 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,456 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,458 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,460 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,463 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,465 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,467 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,469 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,472 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,474 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,476 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,479 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,481 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,484 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,486 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,488 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,491 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,493 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,495 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,497 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,499 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,502 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,505 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,508 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,511 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,513 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,515 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,517 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,520 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,525 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,531 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,536 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,542 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,544 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,547 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,550 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,552 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,555 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,557 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,560 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,564 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,568 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,570 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,573 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,575 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,577 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,580 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,582 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,584 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,587 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,589 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,591 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,593 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,596 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,598 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,601 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,602 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,604 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,606 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,609 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,612 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,614 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,616 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,618 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,621 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,623 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,626 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,629 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,632 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,634 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,637 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,639 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,641 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,644 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,646 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,649 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,651 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,653 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,656 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,659 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,661 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,664 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,668 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,671 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,674 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,676 - INFO - 1 mapping(s) discovered
2026-05-14 11:50:02,680 - INFO - 1 mapping(s) discovered
2026-05-14 11:50:02,684 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,689 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,695 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,701 - INFO - 2 mapping(s) discovered
2026-05-14 11:50:02,706 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,710 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,712 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,714 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,717 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,719 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,722 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,724 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,727 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,729 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,731 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,734 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,736 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,739 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,742 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,745 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,747 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,749 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,752 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,755 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,758 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,760 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,762 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,764 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,767 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,769 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,771 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,773 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,775 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,778 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,783 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,786 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,789 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,791 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,794 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,796 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,798 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,800 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,802 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,805 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,807 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,810 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,812 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,815 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,817 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,820 - INFO - 1 mapping(s) discovered
2026-05-14 11:50:02,824 - INFO - 1 mapping(s) discovered
2026-05-14 11:50:02,828 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,830 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,832 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,835 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,838 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,841 - INFO - 0 mapping(s) discovered
2026-05-14 11:50:02,843 - INFO - 1 mapping(s) discovered
2026-05-14 11:50:02,848 - INFO - 1 mapping(s) discovered
2026-05-14 11:50:02,853 - INFO - 1 mapping(s) discovered
2026-05-14 11:50:02,857 - INFO - 1 mapping(s) discovered
2026-05-14 11:50:02,862 - INFO - 2 mapping(s) discovered

In [71]:
fail = [value for value in raw if value['new_rsmi'] is None]
len(fail)

4962

In [ ]:
for value in raw:
    if value['new_rsmi'] is None:
        new = rbl(rsmi=value['rsmi'], rc=rc[1], return_all=False)
        value['new_rsmi'] = new

In [48]:
from synkit.IO import its_to_gml

print(its_to_gml(rc[1]))

rule [
   ruleID "rule"
   left [
      edge [ source 1 target 2 label "=" ]
      edge [ source 2 target 4 label "-" ]
      edge [ source 3 target 5 label "#" ]
      edge [ source 4 target 6 label "=" ]
   ]
   context [
      node [ id 1 label "C" ]
      node [ id 2 label "C" ]
      node [ id 3 label "C" ]
      node [ id 4 label "C" ]
      node [ id 5 label "C" ]
      node [ id 6 label "C" ]
   ]
   right [
      edge [ source 1 target 2 label "-" ]
      edge [ source 1 target 3 label "-" ]
      edge [ source 2 target 4 label "=" ]
      edge [ source 3 target 5 label "=" ]
      edge [ source 4 target 6 label "-" ]
      edge [ source 5 target 6 label "-" ]
   ]
]

In [49]:
from synkit.IO import gml_to_its

rule_1 = '''
rule [
   ruleID "rule"
   left [
      edge [ source 1 target 3 label "=" ]
      edge [ source 2 target 4 label "=" ]
      edge [ source 3 target 5 label "-" ]
      edge [ source 5 target 6 label "=" ]
   ]
   context [
      node [ id 1 label "C" ]
      node [ id 2 label "C" ]
      node [ id 3 label "C" ]
      node [ id 4 label "C" ]
      node [ id 5 label "C" ]
      node [ id 6 label "C" ]
   ]
   right [
      edge [ source 1 target 2 label "-" ]
      edge [ source 1 target 3 label "-" ]
      edge [ source 2 target 4 label "-" ]
      edge [ source 3 target 5 label "=" ]
      edge [ source 4 target 6 label "-" ]
      edge [ source 5 target 6 label "-" ]
   ]
]
'''

rule_2 = '''
rule [
   ruleID "rule"
   left [
      edge [ source 1 target 2 label "=" ]
      edge [ source 2 target 4 label "-" ]
      edge [ source 3 target 5 label "#" ]
      edge [ source 4 target 6 label "=" ]
   ]
   context [
      node [ id 1 label "C" ]
      node [ id 2 label "C" ]
      node [ id 3 label "C" ]
      node [ id 4 label "C" ]
      node [ id 5 label "C" ]
      node [ id 6 label "C" ]
   ]
   right [
      edge [ source 1 target 2 label "-" ]
      edge [ source 1 target 3 label "-" ]
      edge [ source 2 target 4 label "=" ]
      edge [ source 3 target 5 label "=" ]
      edge [ source 4 target 6 label "-" ]
      edge [ source 5 target 6 label "-" ]
   ]
]
'''

rc_1 = gml_to_its(rule_1)
rc_2 = gml_to_its(rule_2)

In [50]:
print(its_to_gml(rc_1))

rule [
   ruleID "rule"
   left [
      edge [ source 1 target 3 label "=" ]
      edge [ source 2 target 5 label "=" ]
      edge [ source 3 target 4 label "-" ]
      edge [ source 4 target 6 label "=" ]
   ]
   context [
      node [ id 1 label "C" ]
      node [ id 2 label "C" ]
      node [ id 3 label "C" ]
      node [ id 4 label "C" ]
      node [ id 5 label "C" ]
      node [ id 6 label "C" ]
   ]
   right [
      edge [ source 1 target 2 label "-" ]
      edge [ source 1 target 3 label "-" ]
      edge [ source 2 target 5 label "-" ]
      edge [ source 3 target 4 label "=" ]
      edge [ source 4 target 6 label "-" ]
      edge [ source 5 target 6 label "-" ]
   ]
]

In [ ]:
for value in fail:
    new = rbl(rsmi=value['rsmi'], rc=rc[1], return_all=False)
    value['new_rsmi'] = new

In [43]:
fail = [value for value in raw if value['new_rsmi'] is None]
len(fail)

0

In [ ]:
from synkit.Synthesis.Reactor.syn_reactor import SynReactor

reactor = SynReactor(substrate='C1=CCCC=C1.CCOP(=O)(C#CC(F)(F)C(F)(F)F)OCC', template=rc, explicit_h=False, implicit_temp=True)
reactor.smarts

In [ ]:
Standardize().fit('C1=CCCC=C1.CCOP(=O)(C#CC(F)(F)C(F)(F)F)OCC',
                  remove_aam=True)

In [ ]:
fail

In [76]:
from synrxn.io.io import load_df_gz

data = load_df_gz('./Data/aam/enzyme_map.csv.gz')

In [77]:
data

,r_id,ground_truth,rxn,original_id
0,0,[CH3:1][CH:2]=[O:3].[H+].[NH2:4][C:5](=[O:6])[...,CC=O.NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O...,0
1,1,[CH3:1][CH2:2][OH:3].[NH2:4][C:5](=[O:6])[c:7]...,CCO.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP...,1
2,2,[CH3:1][C:2](=[O:3])[CH:4]=[O:5].[H+].[NH2:6][...,CC(=O)C=O.NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)...,25
3,3,[CH3:1][C:2](=[O:3])[CH2:4][OH:5].[NH2:6][C:7]...,CC(=O)CO.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)...,26
4,4,[NH2:1][C:2](=[O:3])[c:4]1[cH:5][cH:6][cH:7][n...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,27
...,...,...,...,...
47969,47969,[NH2:33][c:34]1[n:35][cH:36][n:37][c:38]2[c:39...,N=c1[nH]c(=O)c2ncn([C@@H]3O[C@H](COP(=O)(O)OP(...,349447
47970,47970,[NH2:1][c:2]1[n:3][cH:4][n:5][c:6]2[c:7]1[n:8]...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,349448
47971,47971,[NH2:1][c:2]1[cH:3][cH:4][n:5]([C@@H:6]2[O:7][...,Nc1ccn([C@@H]2O[C@H](COP(=O)(O)O[C@H]3[C@@H](O...,349449
47972,47972,[NH2:56][c:57]1[cH:58][cH:59][n:60]([C@@H:61]2...,N=c1[nH]c(=O)c2ncn([C@@H]3O[C@H](COP(=O)(O)OP(...,349450
47973,47973,[CH2:1]=[C:2]([CH3:3])[CH2:4][CH2:5][O:6][P:7]...,C=C(C)CCOP(=O)(O)OP(=O)(O)OP(=O)(O)O.Nc1ncnc2c...,349457